ini_open("save.ini");

ini_write_real("gamehs", "level1hs", global.level1hs);
ini_write_real("gamehs", "level2hs", global.level2hs);
ini_write_real("gamehs", "level3hs", global.level3hs);
ini_write_real("gamehs", "level4hs", global.level4hs);
ini_write_real("gamehs", "level5hs", global.level5hs);
ini_write_real("gamehs", "level6hs", global.level6hs);
ini_write_real("gamehs", "level7hs", global.level7hs);
ini_write_real("gamehs", "level8hs", global.level8hs);
ini_write_real("gamehs", "level9hs", global.level9hs);
ini_write_real("gamehs", "level10hs", global.level10hs);
ini_write_real("gamehs", "level11hs", global.level11hs);
ini_write_real("gamehs", "level12hs", global.level12hs);
ini_write_real("gamehs", "level13hs", global.level13hs);
ini_write_real("gamehs", "level14hs", global.level14hs);
ini_write_real("gamehs", "level15hs", global.level15hs);
ini_write_real("gamehs", "level16hs", global.level16hs);
ini_write_real("gamehs", "level17hs", global.level17hs);
ini_write_real("gamehs", "level18hs", global.level18hs);
ini_write_real("gamehs", "level19hs", global.level19hs);
ini_write_real("gamehs", "level20hs", global.level20hs);
ini_write_real("gamehs", "level21hs", global.level21hs);
ini_write_real("gamehs", "level22hs", global.level21hs);
ini_write_real("gamehs", "level23hs", global.level23hs);
ini_write_real("gamehs", "level24hs", global.level24hs);
ini_write_real("gamehs", "level25hs", global.level25hs);
ini_write_real("gamehs", "level26hs", global.level26hs);
ini_write_real("gamehs", "level27hs", global.level27hs);
ini_write_real("gamehs", "level28hs", global.level28hs);
ini_write_real("gamehs", "level29hs", global.level29hs);
ini_write_real("gamehs", "level30hs", global.level30hs);

ini_close();
